apiVersion: v1
kind: Service
metadata:
  name: minecraft
  labels:
    name: minecraft
  annotations:
    external-dns.alpha.kubernetes.io/hostname: minecraft.live.willpxxr.com
spec:
  type: LoadBalancer
  selector:
    name: minecraft
  ports:
    - name: minecraft-port
      protocol: TCP
      port: 25565
      targetPort: 25565
