apiVersion: v1
kind: Service
metadata:
  name: minecraft
  labels:
    name: minecraft
spec:
  type: LoadBalancer
  selector:
    name: minecraft
  ports:
    - name: minecraft-port
      protocol: TCP
      port: 25565
      targetPort: 25565
